blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/Chati-dev/Chati.dev/discussions
    about: Ask questions, share ideas, or discuss Chati.dev in our community forum.
